SendaiProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('reg/', include('reg.urls'))
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/urls.py
from django.urls import path
from . import views
from .views import SearchResultsView

urlpatterns = [
    path('', views.main, name='main'),
    path('panel/', views.panel, name='panel'),
    path('report/', views.report, name='report'),
    path('start/', views.start, name='start'),
    path('region/', views.region, name='region'),
    path('search/', SearchResultsView.as_view(), name='search'),
]

reg/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # Вход
    path('', views.signin, name='signin'),
    # Выход
    path('logout', views.logout_view, name='logout'),
    # Регистрация
    path('register', views.register, name='register'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User

def frange(min, max, step):
    while min<=max:
        yield min
        min+=step

class Table(models.Model):
    MONTH_CHOICES = [ (str(round(i, 1)), str(round(i, 1))) for i in frange(0,1, 0.1) ]
    PERSENT = [ (str(i), str(i)) for i in range(0,101) ]
    User = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, verbose_name='Пользователь', )
    A1 = models.CharField('A1 Число погибших результате ЧС на 100 000 человек', max_length=10, null=True, blank=True)
    A2 = models.IntegerField('A2 Число погибших в результате ЧС',null=True, blank=True,)
    A3 = models.IntegerField('A2 Число пострадавших в результате ЧС',null=True, blank=True,)
    B1 = models.CharField('B1 Число непосредственно пострадавших в результате ЧС на 100 000 человек', max_length=10, null=True, blank=True)
    B2 = models.CharField('B2 Число получивших увечья или пострадавших от болезней в результате ЧС на 100 000 человек',max_length=10, null=True, blank=True)
    B3 = models.IntegerField('B3 Число людей, жилища котоsрых были повреждены в результате ЧС',null=True, blank=True)
    B3a = models.IntegerField('B3a Число жилищ/домов, которые были повреждены в результате ЧС',null=True, blank=True)
    B4 = models.IntegerField('B4 Число людей, жилища которых были уничтожены в результате ЧС',null=True, blank=True)
    B4a = models.IntegerField('B4a Число жилищ/домов, которые были уничтожены в результате ЧС',null=True, blank=True)
    C1 = models.CharField('C1 Прямые экономические потери, связанные с бедствиями в отношении мирового валового внутреннего продукта (составной показатель)', max_length=10000000, null=True, blank=True)
    C2 = models.IntegerField('C2 Прямые потери в сельском хозяйстве, связанные с бедствиями.',null=True, blank=True)
    C3 = models.IntegerField('C3 Прямые экономические потери всех других поврежденных или разрушенных производственных активов, связанных с бедствиями. Производственные активы дезагрегированы по отраслям. Страны представляют доклады в отношении имеющихся секторов экономики.',null=True, blank=True)
    C4 = models.IntegerField('C4 Прямые экономические потери в жилищном секторе, связанные с бедствиями',null=True, blank=True)
    C5 = models.IntegerField('C5 Прямые экономические потери в результате повреждения или разрушения важнейших объектов инфраструктуры в результате ЧС',null=True, blank=True)
    C6 = models.IntegerField('C6 Прямые экономические потери в связи с повреждением или разрушением культурного наследия в результате ЧС',null=True, blank=True)
    G3 = models.CharField('G3 Число людей охваченных информационной системой раннего оповещения через местные органы власти или через национальные механизмы распространения информации на 100 000 человек', max_length=10, null=True, blank=True)
    G4 = models.IntegerField('G4 Доля местных органов власти, имеющих план действий в области раннего оповещения',null=True, blank=True)
    G5 = models.IntegerField('G5 Число стран, в которых население получает доступную, понятную, практическую и значимую информацию и оценки, касающиеся риска ЧС, на национальном и местном уровне',null=True, blank=True)
    G6a = models.CharField('G6a Доля населения, подверженного угрозе или риску ЧС, защита которого обеспечивается путем заблаговременной эвакуации на основе раннего оповещения', max_length=10, null=True, blank=True)
    G6a1 = models.IntegerField('G6a1 Число людей, защита которого обеспечивается путем заблаговременной эвакуации на основе экстренного оповещения',null=True, blank=True)
    G6a2 = models.IntegerField('G6a2 Численность населения, проживающего в зоне экстренного оповещения',null=True, blank=True)   
    E10 = models.CharField('E-1.1 Есть временные рамки, целевые задачи и индикатор / 2018',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E11 = models.CharField('E-1.1 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E12 = models.CharField('E-1.2 Задачи и меры, направленные на предотвращение создания риска / 2018',null=True, blank=True, max_length=32,  choices=MONTH_CHOICES)
    E13 = models.CharField('E-1.2 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E14 = models.CharField('E-1.3 Задачи и меры, направленные на снижение существующего риска / 2018',null=True, blank=True, max_length=32,  choices=MONTH_CHOICES)
    E15 = models.CharField('E-1.3 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E16 = models.CharField('E-1.4 Задачи и меры, направленные на укрепление экономической, социальной, санитарной и экологической устойчивости / 2018',null=True, blank=True, max_length=32,  choices=MONTH_CHOICES)
    E17 = models.CharField('E-1.4 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E18 = models.CharField('E-1.5 Рассмотрите рекомендации Приоритета 1, Понимание риска бедствий / 2018',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E19 = models.CharField('E-1.5 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E20 = models.CharField('E-1.6 Рассмотрите рекомендации Приоритета 2, Укрепление управления рисками стихийных бедствий для управления рисками бедствий / 2018',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E21 = models.CharField('E-1.6 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E22 = models.CharField('E-1.7 Рассмотрите рекомендации Приоритета 3, Инвестиции в снижение риска бедствий для обеспечения устойчивости / 2018',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E23 = models.CharField('E-1.7 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E24 = models.CharField('E-1.8 Удовлетворение рекомендаций Приоритета 4, Повышение готовности к стихийным бедствиям для эффективного реагирования и «Улучшение / 2018', null=True, blank=True,  max_length=32, choices=MONTH_CHOICES)
    E25 = models.CharField('E-1.8 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E26 = models.CharField('E-1.9 Содействовать обеспечению согласованности политики и её соблюдения, в частности, с Целями Устойчивого Развития и Парижским соглашением / 2018',null=True, blank=True,max_length=32,  choices=MONTH_CHOICES)
    E27 = models.CharField('E-1.9 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E28 = models.CharField('E-1.10 Имеются механизмы для последующей деятельности, периодически оценивать и публично сообщать о прогрессе / 2018',null=True, blank=True, max_length=32,  choices=MONTH_CHOICES)   
    E29 = models.CharField('E-1.10 2017',null=True, blank=True, max_length=32, choices=MONTH_CHOICES)
    E30 = models.CharField('E-2.1 Имеет цели и меры направленные на снижение существующего риска',null=True, blank=True, max_length=4, choices=PERSENT )
    E31 = models.CharField('E-2.2 Имеет цели и меры направленные на предотвращение появления риска задачи, индикаторы',null=True, blank=True, max_length=4, choices=PERSENT)
    E32 = models.CharField('E-2.3 Имеет цели и меры направленные на укрепление экономической, социальной, экологической устойчивости и устойчивости здравоохранения',null=True, blank=True, max_length=4, choices=PERSENT)
    E33 = models.CharField('E-2.4 Имеет временные рамки, цели и индикаторы',null=True, blank=True, max_length=4, choices=PERSENT)
    E34 = models.CharField('E-2.5 Выполняет рекомендации и предложения Приоритета 1 «Понимание риска бедствий» ',null=True, blank=True, max_length=4, choices=PERSENT)
    E35 = models.CharField('E-2.6 Выполняет рекомендации и предложения Приоритета 2 «совершенствование организационно-правовых рамок управления риском бедствий»',null=True, blank=True, max_length=4, choices=PERSENT)
    E36 = models.CharField('E-2.7 Выполняет рекомендациии предложения Приоритета 3 «Инвестиции в меры по снижению риска бедствий в целях укрепления потенциала противодействия»',null=True, blank=True, max_length=4, choices=PERSENT)
    E37 = models.CharField('E-2.8 Выполняет рекомендации и предложения Приоритета 4 «Повышение готовности к бедствиям для обеспечения эффективного реагирования и внедрение принципа «сделать лучше, чем было» в деятельность по восстановлению, реабилитации и реконструкции» ',null=True, blank=True, max_length=4, choices=PERSENT)
    E38 = models.CharField('E-2.9 Интегрирована на всех уровнях по развитию и планам и политике по искоренению бедности, в особенности ЦУР',null=True, blank=True, max_length=4, choices=PERSENT)
    E39 = models.CharField('E-2.10 Продвигает единение, интеграцию и соответствие планов адаптации к ИК и смягчения его последствий, в соответствии с Парижским ',null=True, blank=True, max_length=4, choices=PERSENT)

class regionchoise(models.Model):
    region = models.CharField('Введите регион',null=False,blank=True, unique=True, max_length=200,)
    
    def __str__(self):
        return self.region

class Usersdate(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, verbose_name='Пользователь',)
    region = models.OneToOneField(regionchoise, on_delete=models.CASCADE, blank=True, verbose_name='Выберите регион',)
    vrp = models.IntegerField('Введите ВВР', null=True, blank=True, )
    people = models.IntegerField('ВВедиет численность населения', null=True, blank=True,)

base/forms.py
from .models import *
from django.forms import *

class TableForm(ModelForm):
    class Meta:
        model = Table
        fields = [
        'A1','A2','A3',
        'B1','B2','B3','B3a','B4','B4a',
        'C1','C2','C3','C4','C5','C6',
        'G3','G4','G5','G6a','G6a1','G6a2',
        'User',
        'E10','E11','E12','E13','E14','E15','E16','E17','E18','E19',
        'E20','E21','E22','E23','E24','E25','E26','E27','E28','E29',
        'E30','E31','E32','E33','E34','E35','E36','E37','E38','E39'
        ]
        widgets = {  
            "A1": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "A2": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "A3": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B1": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B2": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B3": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B3a": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B4": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "B4a": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C1": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C2": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C3": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C4": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C5": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "C6": TextInput(attrs={'class': 'form-control','type': 'text',}),    
            "G1": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G2": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G3": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G4": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G5": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G6a": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G6a1": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "G6a2": TextInput(attrs={'class': 'form-control','type': 'text',}),
            "User": Select(attrs={'class': 'form-control2','type': 'text',}),
            "E10": Select(attrs={'class': 'form-control','type': 'text',}),
            "E11": Select(attrs={'class': 'form-control','type': 'text',}),
            "E12": Select(attrs={'class': 'form-control','type': 'text',}),
            "E13": Select(attrs={'class': 'form-control','type': 'text',}),
            "E14": Select(attrs={'class': 'form-control','type': 'text',}),
            "E15": Select(attrs={'class': 'form-control','type': 'text',}),
            "E16": Select(attrs={'class': 'form-control','type': 'text',}),
            "E17": Select(attrs={'class': 'form-control','type': 'text',}),
            "E18": Select(attrs={'class': 'form-control','type': 'text',}),
            "E19": Select(attrs={'class': 'form-control','type': 'text',}),
            "E20": Select(attrs={'class': 'form-control','type': 'text',}),
            "E21": Select(attrs={'class': 'form-control','type': 'text',}),
            "E22": Select(attrs={'class': 'form-control','type': 'text',}),
            "E23": Select(attrs={'class': 'form-control','type': 'text',}),
            "E24": Select(attrs={'class': 'form-control','type': 'text',}),
            "E25": Select(attrs={'class': 'form-control','type': 'text',}),
            "E26": Select(attrs={'class': 'form-control','type': 'text',}),
            "E27": Select(attrs={'class': 'form-control','type': 'text',}),
            "E28": Select(attrs={'class': 'form-control','type': 'text',}),
            "E29": Select(attrs={'class': 'form-control','type': 'text',}), 
            "E30": Select(attrs={'class': 'form-control','type': 'text',}),
            "E31": Select(attrs={'class': 'form-control','type': 'text',}),
            "E32": Select(attrs={'class': 'form-control','type': 'text',}),
            "E33": Select(attrs={'class': 'form-control','type': 'text',}),
            "E34": Select(attrs={'class': 'form-control','type': 'text',}),
            "E35": Select(attrs={'class': 'form-control','type': 'text',}),
            "E36": Select(attrs={'class': 'form-control','type': 'text',}),
            "E37": Select(attrs={'class': 'form-control','type': 'text',}),
            "E38": Select(attrs={'class': 'form-control','type': 'text',}),
            "E39": Select(attrs={'class': 'form-control','type': 'text',}), 
        }

class UsersdateForm(ModelForm):
    class Meta:
        model = Usersdate
        fields = [
        'region', 'vrp', 'people', 'User'  
        ]
        widgets = {
            "region": Select(attrs={'class':'form-control','type': 'text',}),
            "vrp": TextInput(attrs={'class':'form-control','type': 'text',}),
            "people": TextInput(attrs={'class':'form-control','type': 'text',}),
            "User": Select(attrs={'class': 'form-control2','type': 'text',}),
        }

base/templates/base/base.html
{% load static %}
{% load zz %}

<!doctype html>
<html lang="ru">
  
<head>
  <meta charset="utf-8">
  <title>Мониторинг показателей Сендайской рамочной программы</title>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">
  <link rel="stylesheet" href="{% static 'base/css/style.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/tab.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/reg.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/metadate.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/search.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css'%}">
  <link rel="stylesheet" href="{% static 'base/css/font-awesome.min.css'%}">
</head>

<header>
  <div class="menu_top">
    <div class="header">
      <div class="headerpic">
        <img src="{% static 'base/img/logo.jpg' %}" style="height: 150px; float: right; margin-top: 10px;"> 
      </div>
      <div class="bad">
        <p style="margin-top: 25px; margin-left: 20px; margin-bottom: 1px;"><h9>Федеральное государственное бюджетное образовательное учреждение высшего профессионального образования Академия гражданской защиты МЧС России</h9></p>
        <h8>Научно-исследоватеский центр</h8>          
      </div>  
      {% if request.user.is_authenticated %}
      <div class="user_field">
  
        <label class="lb" for="id_oblast">Ваш регион:</label>                         
        <h8 style="margin-left: 0px !important;">{{ request.user.id|region }}</h8> 
   
        <label class="lb" for="id_vvr">ВРП:</label>              
        <h8 style="margin-left: 0px !important;">{{ request.user.id|vrp }}</h8>

        <label class="lb" for="id_people">Численность населения:</label>
        <h8 style="margin-left: 0px !important;">{{ request.user.id|people }}</h8>                     
      </div>            
      {%  if request.user.is_staff %}
      <div class="report">
        <a href="{% url 'report' %}" class="bott">Общий отчет для отправки</a>
        <a href="/admin" class="bott">Администрационная панель</a> 
        <a href="{% url 'region' %}" class="bott">Проверка Регионов</a>
      </div>
      {% endif %}
    </div>
    <nav class="top-menu">
      <ul class="menu-main">
          <li class="left-item"><a href="{% url 'main' %}">Личный кабинет</a></li>
          <li class="left-item"><a href="{% url 'start' %}">Область</a></li>
          <li class="right-item"><a href="{% url 'logout' %}">Выход из аккаунта</a></li>
          <li class="right-item"><a href="{% url 'panel' %}">Отчет о заполнении</a></li>   
      </ul>
      <a class="navbar-logo" href="{% url 'start' %}"><img src="{% static 'base/img/rose.png' %}" style="height: 150px;" ></a>   
    </nav> 
      {% else %}
      <div class="user_reg"> 
        <a href="{% url 'signin' %}" class="button user_reg2">Войти</a>
        <a href="{% url 'register' %}" class="button user_reg2">Регистрация</a>
      </div>        
  </div>
  {% endif %} 
</header>

<body>   
  {% block body %}
  {% endblock %}
</body>

<footer class="my-5 pt-5 text-muted text-center text-small">
      <p class="mb-1">&copy; 2021 АГЗ МЧС России</p>
</footer>
</html>

base/templates/base/panel.html
{% extends 'base/base.html' %}
{% block body %}
{% if table %}
<h3 style="text-align: center; margin-top: 48px; font-style: italic;">Отчеты</h3>
        <div class="oblozhka">
            <div style="margin-top: 5%;text-align: center;">
                <table border="1" style="margin-left: 85px; background-color: #f0f0f0;" width="90%" cellpadding="5">
                    <div class="block-body-user">
                    </div>
                    <tbody>                  
                        <tr>
                            <th rowspan="2">Блок A</th>
                            <th>A1</th>
                            <th>A2</th>
                        </tr>
                        <tr>
                            <td> {{ table.A1 }} </td>
                            <td> {{ table.A2 }}  </td>
                        </tr>
                        <tr>
                            <th rowspan="2">Блок B</th>
                            <th>B1</th>
                            <th>B2</th>
                            <th>B3</th>
                            <th>B3a</th>
                            <th>B4</th>
                            <th>B4a</th>
                        </tr>
                        <tr>
                            <td> {{ table.B1 }} </td>
                            <td> {{ table.B2 }} </td>
                            <td> {{ table.B3 }} </td>
                            <td> {{ table.B3a }} </td>
                            <td> {{ table.B4 }} </td>
                            <td> {{ table.B4a }} </td>
                        </tr>
                        <tr>
                            <th rowspan="2">Блок C</th>
                            <th>C1</th>
                            <th>C2</th>
                            <th>C3</th>
                            <th>C4</th>
                            <th>C5</th>
                            <th>C6</th>
                        </tr>
                        <tr>
                            <td> {{ table.C1 }} </td>
                            <td> {{ table.C2 }} </td>
                            <td> {{ table.C3 }} </td>
                            <td> {{ table.C4 }} </td>
                            <td> {{ table.C5 }} </td>
                            <td> {{ table.C6 }} </td>
                        </tr>           
                        <tr>
                            <th rowspan="2">Блок G</th> 
                            <th>G3</th>
                            <th>G4</th>
                            <th>G5</th>
                            <th>G6a</th>
                            <th>G6a1</th>
                            <th>G6a2</th>
                        </tr>
                        <tr>
                            <td> {{ table.G3 }} </td>
                            <td> {{ table.G4 }} </td>
                            <td> {{ table.G5 }} </td>
                            <td> {{ table.G6a }} </td>
                            <td> {{ table.G6a1 }} </td>
                            <td> {{ table.G6a2 }} </td>
                        </tr>
                        <tr>
                            <th rowspan="2">Блок E-1</th>
                            <th>E-1</th>
                            <th>E-2</th>
                            <th>E-3</th>
                            <th>E-4</th>
                            <th>E-5</th>
                            <th>E-6</th>
                            <th>E-7</th>
                            <th>E-8</th>
                            <th>E-9</th>
                            <th>E-10</th>
                        </tr>
                        <tr>
                            <td> {{ table.E10 }} </td>
                            <td> {{ table.E11 }} </td>
                            <td> {{ table.E12 }} </td>
                            <td> {{ table.E13 }} </td>
                            <td> {{ table.E14 }} </td>
                            <td> {{ table.E15 }} </td>
                            <td> {{ table.E16 }} </td>
                            <td> {{ table.E17 }} </td>
                            <td> {{ table.E18 }} </td>
                            <td> {{ table.E19 }} </td>                       
                        </tr>
                        <tr>
                            <th rowspan="2">Блок E-2</th>
                            <th>E-2.1</th>
                            <th>E-2.2</th>
                            <th>E-2.3</th>
                            <th>E-2.4</th>
                            <th>E-2.5</th>
                            <th>E-2.6</th>
                            <th>E-2.7</th>
                            <th>E-2.8</th>
                            <th>E-2.9</th>
                            <th>E-2.10</th>
                        </tr>
                        <tr>
                            <td> {{ table.E20 }} </td>
                            <td> {{ table.E21 }} </td>
                            <td> {{ table.E22 }} </td>
                            <td> {{ table.E23 }} </td>
                            <td> {{ table.E24 }} </td>
                            <td> {{ table.E25 }} </td>
                            <td> {{ table.E26 }} </td>
                            <td> {{ table.E27 }} </td>
                            <td> {{ table.E28 }} </td>
                            <td> {{ table.E29 }} </td>
                        </tr>
                    </tbody>
                </table> 
                <br>
            </div>
        </div>  
{% else %} 

<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </ul>
    {% endif %}
    <br>
</div>      

{% endif %}
      
{% endblock %}

base/templates/base/region.html
{% extends 'base/base.html' %}
{% block body %}
        <div class="searchdiv">
        <h3 style="text-align: center; margin-top: 48px; font-style: italic;">Выберите регион</h3>
            <form id="searchform" action="{% url 'search' %}" method="get" >
                <div class="shadow">{{ region.form.region }}</div>
                <button class="searchbat">Показать</button>
            </form>
        </div>      
{% endblock %}

base/templates/base/start.html
{% extends 'base/base.html' %}
{% block body %}
<h3 style="text-align: center; margin-top: 5%; font-style: italic;">Мониторинг показателей Сендайской рамочной программы</h3>
<h3 style="text-align: center;  font-style: italic;">Добро пожаловать на наш сайт введите данные своей области</h3>
<form method="post" action="" enctype="multipart/form-data">
  {% if is_exist %}        
      <h1 style="margin-left: 35%; margin-top: 5%;">Ваши данные отправлены</h1>
      <br>
      
{% else %}
    <div class="metadate">
      <div class="date" >
            {% csrf_token %}
            <p>
                <label for="id_oblast">Регион:</label>
                {{ form.region }}
              </p>
              <p>
                <label for="id_vvr">ВРП:</label>
                {{ form.vrp }}
              </p>
              <p>
                <label for="id_people">Численность населения:</label>
                {{ form.people }}
              </p>
              <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Сохранить</button>
              </hr> 
      </div>
    </div>         
</form>
{% endif %}  
{% endblock%}